---

# ---------------------------------------------------------------
# - name: "REX-Ray: vendor agnostic storage orchestration engine."
#   become: true
#   shell:  curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -
#   args:
#     chdir: /tmp
- name: "REX-Ray: vendor agnostic storage orchestration engine (0: check installed)"
  command: dpkg-query -l rexray
  register: rexray_installed_status
  changed_when: false

- name: "REX-Ray: vendor agnostic storage orchestration engine (1: download)"
  become: true
  get_url:
    url: https://dl.bintray.com/emccode/rexray/install
    dest: /usr/local/src/hsz/rex-ray-install.sh
  register: rexray_download_status
  when:
    - not (rexray_installed_status.rc == 0)

- name: "REX-Ray: vendor agnostic storage orchestration engine (2: install)"
  become: true
  shell: bash /usr/local/src/hsz/rex-ray-install.sh
  when:
    - not (rexray_installed_status.rc == 0)

