---
language: python
python:
    - 2.7

sudo: required

services:
 - docker

install:
  - sudo apt-get install apt-transport-https ca-certificates
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip2 install --upgrade pip setuptools wheel docker-compose
  - sudo docker-compose --version

script:
  - sudo make build
