---

- name: prepae folder structure
  file:
    path: /usr/local/src/hsz
    state: directory

# weave
# flannel

# ---------------------------------------------------------------
- name: pre-requisites for NFS/CIFS plugin
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - nfs-common
    - cifs-utils

# ---------------------------------------------------------------
# - name: "REX-Ray: vendor agnostic storage orchestration engine."
#   become: true
#   shell:  curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -
#   args:
#     chdir: /tmp

- name: "REX-Ray: vendor agnostic storage orchestration engine (1)"
  become: true
  get_url:
    url: https://dl.bintray.com/emccode/rexray/install
    dest: /usr/local/src/hsz/rex-ray-install.sh
  register: rexray_download_status

- name: "REX-Ray: vendor agnostic storage orchestration engine (2)"
  become: true
  shell: bash /usr/local/src/hsz/rex-ray-install.sh
  when: rexray_download_status.changed

# ---------------------------------------------------------------
# https://dzone.com/articles/mount-aws-efs-nfs-or-cifssamba-volumes-in-docker
- name: "NetShare: Docker NFS, AWS EFS & Samba/CIFS Volume Plugin (1)"
  become: true
  get_url:
    url: https://github.com/gondor/docker-volume-netshare/releases/download/v{{ VERSIONS['d-v-netshare'] |mandatory }}/docker-volume-netshare_{{ VERSIONS['d-v-netshare'] |mandatory }}_amd64.deb
    dest: /usr/local/src/hsz/docker-volume-netshare_{{ VERSIONS['d-v-netshare'] |mandatory }}_amd64.deb
  register: netshare_downloaded

- name: "NetShare: Docker NFS, AWS EFS & Samba/CIFS Volume Plugin (2)"
  become: true
  apt:
    deb: /usr/local/src/hsz/docker-volume-netshare_{{ VERSIONS['d-v-netshare'] |mandatory }}_amd64.deb
  when: netshare_downloaded.changed
  register: netshare_installed

- name: "NetShare: Docker NFS, AWS EFS & Samba/CIFS Volume Plugin (3)"
  become: true
  service:
    name:   docker-volume-netshare
    state: started
  when: ((netshare_downloaded is defined) and netshare_downloaded.changed) or ((netshare_installed is defined) or netshare_installed.changed)

# # ---------------------------------------------------------------
# - name: "Docker Volume Driver for Azure File Storage"
#   become: true
#   ....
