---
version: '2'

services:
  postcfg-dh-drv--vol:
    build: .

    image: highskillz/docker-postcfg-dm-host
    image: highskillz/docker-postcfg-dm-host:${TAG_VERSION}

    container_name: postcfg-dm-host   # prevent scaling out

    # based on:
    #   https://github.com/nathanleclaire/dockerfiles/tree/master/ansible
    #
    # "host" networking means ssh to localhost is ssh to docker-host (!!!)
    network_mode: "host"

    volumes:
      # enables access to the docker-host by ansible
      - /root/.ssh:/hostssh

      # persists the logs for a while
      - postcfg_logs:/var/log/ansible

  postcfg-dh--sslh:
    image: amondit/sslh
    # environment:
    #     SSH_PORT:      60022
    # #    SSH_PORT:         22
    # #    HTTPS_PORT:     8443
    # #    OPENVPN_PORT:   1194
    network_mode: "host"
    ports:
      - "443:443"

volumes:
  # we want to persist the logs
  postcfg_logs:
    external:
        name: postcfg-logs
        # docker volume create --driver=local --name=postcfg-logs
